### ISSUE TITLE
FC when clicking on Download Finished Notifications

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hoanglanton/cyanogen-updater#102]
```
After download Clikc on the Download Finished not:
p.ui.ApplyUploadActivity}: java.lang.NullPointerException
E/AndroidRuntime( 4391):    at
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2324)
E/AndroidRuntime( 4391):    at
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2417)
E/AndroidRuntime( 4391):    at
android.app.ActivityThread.access$2100(ActivityThread.java:116)
E/AndroidRuntime( 4391):    at
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
E/AndroidRuntime( 4391):    at
android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 4391):    at android.os.Looper.loop(Looper.java:123)
E/AndroidRuntime( 4391):    at
android.app.ActivityThread.main(ActivityThread.java:4203)
E/AndroidRuntime( 4391):    at java.lang.reflect.Method.invokeNative(Native
Method)
E/AndroidRuntime( 4391):    at java.lang.reflect.Method.invoke(Method.java:521)
E/AndroidRuntime( 4391):    at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
E/AndroidRuntime( 4391):    at
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:549)
E/AndroidRuntime( 4391):    at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 4391): Caused by: java.lang.NullPointerException
E/AndroidRuntime( 4391):    at
android.content.ContextWrapper.getPackageName(ContextWrapper.java:120)
E/AndroidRuntime( 4391):    at
android.preference.PreferenceManager.getDefaultSharedPreferencesName(PreferenceM
anager.java:352)
E/AndroidRuntime( 4391):    at
android.preference.PreferenceManager.getDefaultSharedPreferences(PreferenceManag
er.java:347)
E/AndroidRuntime( 4391):    at
cmupdaterapp.utils.Preferences.getPreferences(Preferences.java:46)
E/AndroidRuntime( 4391):    at
cmupdaterapp.ui.ApplyUploadActivity$ApplyUpdateListener.<init>(ApplyUploadActivi
ty.java:64)
E/AndroidRuntime( 4391):    at
cmupdaterapp.ui.ApplyUploadActivity.<init>(ApplyUploadActivity.java:56)
E/AndroidRuntime( 4391):    at java.lang.Class.newInstanceImpl(Native Method)
E/AndroidRuntime( 4391):    at java.lang.Class.newInstance(Class.java:1472)
E/AndroidRuntime( 4391):    at
android.app.Instrumentation.newActivity(Instrumentation.java:1097)
E/AndroidRuntime( 4391):    at
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2316)

```

Original issue reported on code.google.com by `FireFart` on 11 Sep 2009 at 6:27

**Comment by GoogleCodeExporter** [comment]
```
happend again:
10-31 12:25:40.723 E/AndroidRuntime( 1394): java.lang.RuntimeException: Unable 
to resume activity 
{cmupdaterapp.ui/cmupdaterapp.ui.DownloadActivity}: 
java.lang.NullPointerException
10-31 12:25:40.723 E/AndroidRuntime( 1394): at 
android.app.ActivityThread.performResumeActivity(ActivityThread.java:2851)
10-31 12:25:40.723 E/AndroidRuntime( 1394): at 
android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2866)
10-31 12:25:40.723 E/AndroidRuntime( 1394): at 
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420)
10-31 12:25:40.723 E/AndroidRuntime( 1394): at 
android.app.ActivityThread.access$2100(ActivityThread.java:116)
10-31 12:25:40.723 E/AndroidRuntime( 1394): at 
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
10-31 12:25:40.723 E/AndroidRuntime( 1394): at 
android.os.Handler.dispatchMessage(Handler.java:99)
10-31 12:25:40.723 E/AndroidRuntime( 1394): at 
android.os.Looper.loop(Looper.java:123)
10-31 12:25:40.723 E/AndroidRuntime( 1394): at 
android.app.ActivityThread.main(ActivityThread.java:4203)
10-31 12:25:40.723 E/AndroidRuntime( 1394): at 
java.lang.reflect.Method.invokeNative(Native Method)
10-31 12:25:40.723 E/AndroidRuntime( 1394): at 
java.lang.reflect.Method.invoke(Method.java:521)
10-31 12:25:40.723 E/AndroidRuntime( 1394): at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
10-31 12:25:40.723 E/AndroidRuntime( 1394): at 
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:549)
10-31 12:25:40.723 E/AndroidRuntime( 1394): at 
dalvik.system.NativeStart.main(Native Method)
10-31 12:25:40.723 E/AndroidRuntime( 1394): Caused by: 
java.lang.NullPointerException
10-31 12:25:40.723 E/AndroidRuntime( 1394): at 
cmupdaterapp.ui.DownloadActivity.onResume(DownloadActivity.java:115)
10-31 12:25:40.723 E/AndroidRuntime( 1394): at 
android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1225)
10-31 12:25:40.723 E/AndroidRuntime( 1394): at 
android.app.Activity.performResume(Activity.java:3559)
10-31 12:25:40.723 E/AndroidRuntime( 1394): at 
android.app.ActivityThread.performResumeActivity(ActivityThread.java:2838)
10-31 12:25:40.723 E/AndroidRuntime( 1394): ... 12 more
```

Original comment by `FireFart` on 1 Nov 2009 at 9:18

**Comment by GoogleCodeExporter** [comment]
```
the app looses the context to the Service (to reproduce: start download, home 
button, start excahnge mail --> 
low memory), click on notification
```

Original comment by `FireFart` on 22 Dec 2009 at 8:02

**Comment by GoogleCodeExporter** [comment]
```
fixed
```

Original comment by `FireFart` on 13 Jan 2010 at 5:58
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `FireFart` on 17 Feb 2010 at 6:38
- Changed state: **Verified**
