### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hoanglanton/cyanogen-updater#109]
```
0): Uncaught handler: thread main exiting due to uncaught exception
D/dalvikvm(  450): GC(0) freed 8301 objects / 486184 bytes in 107ms
E/AndroidRuntime(  450): java.lang.RuntimeException: Unable to stop activity 
{cmupdaterapp.ui/cmupdaterapp.ui.MainActivity}: 
java.lang.IllegalArgumentException: Service 
not registered: cmupdaterapp.ui.MainActivity$1@4378f1c8
E/AndroidRuntime(  450):    at 
android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3316)
E/AndroidRuntime(  450):    at 
android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3382)
E/AndroidRuntime(  450):    at 
android.app.ActivityThread.access$2700(ActivityThread.java:116)
E/AndroidRuntime(  450):    at 
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1826)
E/AndroidRuntime(  450):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(  450):    at android.os.Looper.loop(Looper.java:123)
E/AndroidRuntime(  450):    at 
android.app.ActivityThread.main(ActivityThread.java:4203)
E/AndroidRuntime(  450):    at java.lang.reflect.Method.invokeNative(Native 
Method)
E/AndroidRuntime(  450):    at java.lang.reflect.Method.invoke(Method.java:521)
E/AndroidRuntime(  450):    at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
E/AndroidRuntime(  450):    at 
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:549)
E/AndroidRuntime(  450):    at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(  450): Caused by: java.lang.IllegalArgumentException: Service 
not registered: 
cmupdaterapp.ui.MainActivity$1@4378f1c8
E/AndroidRuntime(  450):    at 
android.app.ActivityThread$PackageInfo.forgetServiceDispatcher(ActivityThread.ja
va:880)
E/AndroidRuntime(  450):    at 
android.app.ApplicationContext.unbindService(ApplicationContext.java:865)
E/AndroidRuntime(  450):    at 
android.content.ContextWrapper.unbindService(ContextWrapper.java:324)
E/AndroidRuntime(  450):    at 
cmupdaterapp.ui.MainActivity.onStop(MainActivity.java:793)
E/AndroidRuntime(  450):    at 
android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1245)
E/AndroidRuntime(  450):    at 
android.app.Activity.performStop(Activity.java:3593)
E/AndroidRuntime(  450):    at 
android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3311)

```

Original issue reported on code.google.com by `FireFart` on 13 Sep 2009 at 9:05

**Comment by GoogleCodeExporter** [comment]
```
fixed
```

Original comment by `FireFart` on 14 Sep 2009 at 4:58
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `FireFart` on 14 Sep 2009 at 5:13
- Changed state: **Verified**
