### ISSUE TITLE
FC when try to add a new theme server

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hoanglanton/cyanogen-updater#138]
```
First this is not a Bugtracker for Cyanogen-Rom Bugs. Only for the updater.
The other Bugtracker can be found here:
http://code.google.com/p/cyanogenmod/issues/list

What steps will reproduce the problem?
1.on the program click on menu then config 
2.go to theme update settings then manage theme servers
3.click on menu - add theme server

What is the expected output? What do you see instead?
when i clicked on add theme server i got Force close message
when i clicked on the button the program returns to last state.. 

What ROM are you running?(including Version)
cm-4.1.9999

Please provide a logcat of the issue:
===========================================================================
(ThemeListNewActivity.java:45)
E/AndroidRuntime( 1419):        at
android.app.Instrumentation.callActivityOnCre
ate(Instrumentation.java:1123)
E/AndroidRuntime( 1419):        at
android.app.ActivityThread.performLaunchActiv
ity(ActivityThread.java:2364)
E/AndroidRuntime( 1419):        ... 11 more
I/Process (  146): Sending signal. PID: 1419 SIG: 3
I/dalvikvm( 1419): threadid=7: reacting to signal 3
I/dalvikvm( 1419): Wrote stack trace to '/data/anr/traces.txt'
D/NetworkLocationProvider(  146): getLocation(): triggering a wifi scan
I/wpa_supplicant( 1136): CTRL-EVENT-SCAN-RESULTS  Ready
W/ActivityManager(  146): Launch timeout has expired, giving up wake lock!
W/ActivityManager(  146): Activity idle timeout for HistoryRecord{43a182e8
cmupd
aterapp.ui/.ThemeListNewActivity}
D/ForecastProvider(  930): query() with
uri=content://com.androidapps.widget.wea
ther2/appwidgets/26
D/ForecastProvider(  930): query() with
uri=content://com.androidapps.widget.wea
ther2/appwidgets/26
D/Sensors (  146): sensors=00000000, real=00000000
D/AKMD    (  132): Compass CLOSE
D/KeyguardViewMediator(  146): Statusbar locked
D/SurfaceFlinger(  146): About to give-up screen, flinger = 0x16b128
D/dalvikvm(  146): GC(2) freed 3794 objects / 183184 bytes in 293ms
W/ActivityManager(  146): Activity pause timeout for HistoryRecord{43a182e8
cmup
daterapp.ui/.ThemeListNewActivity}
D/WifiService(  146): ACTION_SCREEN_OFF
D/WifiService(  146): setting ACTION_DEVICE_IDLE timer for 900000ms
D/KeyguardViewMediator(  146): wakeWhenReadyLocked(82)
D/KeyguardViewMediator(  146): Statusbar locked
D/KeyguardViewMediator(  146): handleWakeWhenReady(82)
D/KeyguardViewMediator(  146): pokeWakelock(5000)
D/AKMD    (  132): Compass OPEN
D/Sensors (  146): sensors=00000001, real=00000001
W/WindowManager(  146): No focus window, dropping: KeyEvent{action=1
code=82 rep
eat=0 meta=0 scancode=139 mFlags=8}
D/ForecastProvider(  930): query() with
uri=content://com.androidapps.widget.wea
ther2/appwidgets/26
D/ForecastProvider(  930): query() with
uri=content://com.androidapps.widget.wea
ther2/appwidgets/26
D/SurfaceFlinger(  146): Screen about to return, flinger = 0x16b128
D/WifiService(  146): ACTION_SCREEN_ON
I/WindowManager(  146): onOrientationChanged, rotation changed to 0
D/dalvikvm(  930): GC(2) freed 1182 objects / 401952 bytes in 102ms
D/KeyguardViewMediator(  146): pokeWakelock(5000)
D/dalvikvm(  563): GC(2) freed 1892 objects / 69152 bytes in 156ms
D/KeyguardViewMediator(  146): pokeWakelock(5000)
D/KeyguardViewMediator(  146): pokeWakelock(7000)
D/KeyguardViewMediator(  146): Statusbar unlocked
I/Process ( 1419): Sending signal. PID: 1419 SIG: 9
I/WindowManager(  146): WIN DEATH: Window{43cdeda8
cmupdaterapp.ui/cmupdaterapp.
ui.MainActivity paused=false}
I/ActivityManager(  146): Process cmupdaterapp.ui (pid 1419) has died.
I/WindowManager(  146): WIN DEATH: Window{4396c098
cmupdaterapp.ui/cmupdaterapp.
ui.ConfigActivity paused=false}
I/WindowManager(  146): WIN DEATH: Window{43b06720 Theme Update Settings
paused=
false}
I/WindowManager(  146): WIN DEATH: Window{43b5c948
cmupdaterapp.ui/cmupdaterapp.
ui.ThemeListActivity paused=false}
I/ActivityManager(  146): Start proc cmupdaterapp.ui for activity
cmupdaterapp.u
i/.ThemeListActivity: pid=1437 uid=10066 gids={3003, 1015}
I/ActivityManager(  146): Low Memory: No more background processes.
W/UsageStats(  146): Something wrong here, didn't expect cmupdaterapp.ui to
be r
esumed
D/cmupdater( 1437): ThemeListActivity: Opening Database
W/InputManagerService(  146): Got RemoteException sending setActive(false)
notif
ication to pid 1419 uid 10066
I/ActivityManager(  146): Displayed activity
cmupdaterapp.ui/.ThemeListActivity:
 1126 ms (total 69466 ms)
W/AnySoftKeyboard( 1248): The OS has reported that it is low on memory!.
I'll tr
y to clear some cache.
D/AnySoftKeyboard( 1248): makeKeyboards: force:false maxWidth:320
mLastDisplayWi
dth320
D/dalvikvm( 1248): GC(1) freed 112 objects / 6704 bytes in 277ms
D/skia    (  146): purging 114K from font cache [15 entries]
D/dalvikvm(  146): GC(1) freed 4299 objects / 214368 bytes in 266ms
D/dalvikvm(  314): GC(1) freed 290 objects / 12720 bytes in 133ms
D/skia    (  563): purging 20K from font cache [3 entries]
D/dalvikvm(  563): GC(1) freed 710 objects / 27472 bytes in 165ms
D/dalvikvm(  930): GC(1) freed 554 objects / 296768 bytes in 122ms
D/dalvikvm(  321): GC(1) freed 135 objects / 9616 bytes in 181ms
D/dalvikvm(  485): GC(1) freed 7 objects / 240 bytes in 120ms
D/AnySoftKeyboard( 1248): Event: Key:20 Shift:false ALT:false Repeats:0
D/AnySoftKeyboard( 1248): makeKeyboards: force:false maxWidth:320
mLastDisplayWi
dth320
D/AnySoftKeyboard( 1248): makeKeyboards: force:false maxWidth:320
mLastDisplayWi
dth320
D/AnySoftKeyborad( 1248): Asking '╫נ╫á╫ע╫£╫ש╫¬' to translate 
key: 20
V/AnySoftKeyboard( 1248): Hard Keyboard Action before translation: Shift:
false,
 Alt: false, Key code: 20, changed: false
V/AnySoftKeyboard( 1248): Hard Keyboard Action after translation: Shift: false,
Alt: false, Key code: 20, changed: false
D/AnySoftKeyborad( 1248): '╫נ╫á╫ע╫£╫ש╫¬' did not translated 
key 20.
D/dalvikvm(  347): GC(1) freed 22 objects / 904 bytes in 162ms
D/AnySoftKeyboard( 1248): Event: Key:21 Shift:false ALT:false Repeats:0
D/AnySoftKeyboard( 1248): makeKeyboards: force:false maxWidth:320
mLastDisplayWi
dth320
D/AnySoftKeyboard( 1248): makeKeyboards: force:false maxWidth:320
mLastDisplayWi
dth320
D/AnySoftKeyborad( 1248): Asking '╫נ╫á╫ע╫£╫ש╫¬' to translate 
key: 21
V/AnySoftKeyboard( 1248): Hard Keyboard Action before translation: Shift:
false,
 Alt: false, Key code: 21, changed: false
V/AnySoftKeyboard( 1248): Hard Keyboard Action after translation: Shift: false,
Alt: false, Key code: 21, changed: false
D/AnySoftKeyborad( 1248): '╫נ╫á╫ע╫£╫ש╫¬' did not translated 
key 21.
D/ForecastProvider(  930): query() with
uri=content://com.androidapps.widget.wea
ther2/appwidgets/26
D/ForecastProvider(  930): query() with
uri=content://com.androidapps.widget.wea
ther2/appwidgets/26
D/AnySoftKeyboard( 1248): Event: Key:82 Shift:false ALT:false Repeats:0
D/AnySoftKeyboard( 1248): makeKeyboards: force:false maxWidth:320
mLastDisplayWi
dth320
D/AnySoftKeyboard( 1248): makeKeyboards: force:false maxWidth:320
mLastDisplayWi
dth320
D/AnySoftKeyborad( 1248): Asking '╫נ╫á╫ע╫£╫ש╫¬' to translate 
key: 82
V/AnySoftKeyboard( 1248): Hard Keyboard Action before translation: Shift:
false,
 Alt: false, Key code: 82, changed: false
V/AnySoftKeyboard( 1248): Hard Keyboard Action after translation: Shift: false,
Alt: false, Key code: 82, changed: false
D/AnySoftKeyborad( 1248): '╫נ╫á╫ע╫£╫ש╫¬' did not translated 
key 82.
I/ActivityManager(  146): Starting activity: Intent {
cmp=cmupdaterapp.ui/.Theme
ListNewActivity (has extras) }
D/AndroidRuntime( 1437): Shutting down VM
W/dalvikvm( 1437): threadid=3: thread exiting with uncaught exception
(group=0x4
001e1c0)
E/AndroidRuntime( 1437): Uncaught handler: thread main exiting due to
uncaught e
xception
E/AndroidRuntime( 1437): java.lang.RuntimeException: Unable to start
activity Co
mponentInfo{cmupdaterapp.ui/cmupdaterapp.ui.ThemeListNewActivity}:
java.lang.Nul
lPointerException
E/AndroidRuntime( 1437):        at
android.app.ActivityThread.performLaunchActiv
ity(ActivityThread.java:2401)
E/AndroidRuntime( 1437):        at
android.app.ActivityThread.handleLaunchActivi
ty(ActivityThread.java:2417)
E/AndroidRuntime( 1437):        at
android.app.ActivityThread.access$2100(Activi
tyThread.java:116)
E/AndroidRuntime( 1437):        at
android.app.ActivityThread$H.handleMessage(Ac
tivityThread.java:1794)
E/AndroidRuntime( 1437):        at
android.os.Handler.dispatchMessage(Handler.ja
va:99)
E/AndroidRuntime( 1437):        at android.os.Looper.loop(Looper.java:123)
E/AndroidRuntime( 1437):        at
android.app.ActivityThread.main(ActivityThrea
d.java:4203)
E/AndroidRuntime( 1437):        at java.lang.reflect.Method.invokeNative(Native
Method)
E/AndroidRuntime( 1437):        at
java.lang.reflect.Method.invoke(Method.java:5
21)
E/AndroidRuntime( 1437):        at
com.android.internal.os.ZygoteInit$MethodAndA
rgsCaller.run(ZygoteInit.java:791)
E/AndroidRuntime( 1437):        at
com.android.internal.os.ZygoteInit.main(Zygot
eInit.java:549)
E/AndroidRuntime( 1437):        at dalvik.system.NativeStart.main(Native
Method)

E/AndroidRuntime( 1437): Caused by: java.lang.NullPointerException
E/AndroidRuntime( 1437):        at
cmupdaterapp.ui.ThemeListNewActivity.onCreate
(ThemeListNewActivity.java:45)
E/AndroidRuntime( 1437):        at
android.app.Instrumentation.callActivityOnCre
ate(Instrumentation.java:1123)
E/AndroidRuntime( 1437):        at
android.app.ActivityThread.performLaunchActiv
ity(ActivityThread.java:2364)
E/AndroidRuntime( 1437):        ... 11 more
I/Process (  146): Sending signal. PID: 1437 SIG: 3
I/dalvikvm( 1437): threadid=7: reacting to signal 3
I/dalvikvm( 1437): Wrote stack trace to '/data/anr/traces.txt'
D/KeyguardUpdateMonitor(  146): We've updated the battery level!
LockScreen.java
 = 56
D/KeyguardUpdateMonitor(  146): We've updated the battery level!
KeyguardUpdateM
onitor.java = 56
D/MountListener(  146): handleEvent ums_connected
D/WifiService(  146): ACTION_BATTERY_CHANGED pluggedType: 2
I/ActivityManager(  146): Start proc android.process.media for content provider
com.android.providers.media/.MediaProvider: pid=1449 uid=10019 gids={1006,
1015,
 2001, 3003}
I/ActivityThread( 1449): Publishing provider media:
com.android.providers.media.
MediaProvider
V/MediaProvider( 1449): Attached volume: internal
V/MediaProvider( 1449): /sdcard volume ID: 338294160
V/MediaProvider( 1449): Attached volume: external
I/ActivityThread( 1449): Publishing provider downloads:
com.android.providers.do
wnloads.DownloadProvider
I/ActivityThread( 1449): Publishing provider drm:
com.android.providers.drm.DrmP
rovider
W/AudioFlinger(  127): write blocked for 92 msecs
I/ActivityManager(  146): Process android.process.media (pid 1449) has died.
I/ActivityManager(  146): Low Memory: No more background processes.
W/ActivityManager(  146): Launch timeout has expired, giving up wake lock!
W/ActivityManager(  146): Activity idle timeout for HistoryRecord{43b58c58
cmupd
aterapp.ui/.ThemeListNewActivity}
D/ForecastProvider(  930): query() with
uri=content://com.androidapps.widget.wea
ther2/appwidgets/26
D/ForecastProvider(  930): query() with
uri=content://com.androidapps.widget.wea
ther2/appwidgets/26
D/dalvikvm(  930): GC(2) freed 1177 objects / 401512 bytes in 119ms
D/dalvikvm(  146): GC(2) freed 14100 objects / 1020824 bytes in 269ms
D/Sensors (  146): sensors=00000000, real=00000000
D/KeyguardViewMediator(  146): Statusbar locked
D/AKMD    (  132): Compass CLOSE
D/WifiService(  146): ACTION_SCREEN_OFF
D/WifiService(  146): setting ACTION_DEVICE_IDLE timer for 900000ms
D/SurfaceFlinger(  146): About to give-up screen, flinger = 0x16b128
W/ActivityManager(  146): Activity pause timeout for HistoryRecord{43b58c58
cmup
daterapp.ui/.ThemeListNewActivity}
D/dalvikvm(  146): GC(2) freed 1812 objects / 86488 bytes in 263ms
D/dalvikvm(  321): GC(1) freed 180 objects / 15640 bytes in 142ms
D/dalvikvm(  347): GC(1) freed 21 objects / 944 bytes in 125ms
D/KeyguardViewMediator(  146): wakeWhenReadyLocked(82)
D/KeyguardViewMediator(  146): Statusbar locked
D/KeyguardViewMediator(  146): handleWakeWhenReady(82)
D/KeyguardViewMediator(  146): pokeWakelock(5000)
D/AKMD    (  132): Compass OPEN
D/Sensors (  146): sensors=00000001, real=00000001
D/SurfaceFlinger(  146): Screen about to return, flinger = 0x16b128
D/ForecastProvider(  930): query() with
uri=content://com.androidapps.widget.wea
ther2/appwidgets/26
D/ForecastProvider(  930): query() with
uri=content://com.androidapps.widget.wea
ther2/appwidgets/26
D/WifiService(  146): ACTION_SCREEN_ON
I/WindowManager(  146): onOrientationChanged, rotation changed to 0
D/KeyguardViewMediator(  146): pokeWakelock(7000)
D/KeyguardViewMediator(  146): Statusbar unlocked
I/Process ( 1437): Sending signal. PID: 1437 SIG: 9
I/ActivityManager(  146): Process cmupdaterapp.ui (pid 1437) has died.
I/WindowManager(  146): WIN DEATH: Window{43be3c20
cmupdaterapp.ui/cmupdaterapp.
ui.ThemeListActivity paused=false}
I/ActivityManager(  146): Start proc cmupdaterapp.ui for activity
cmupdaterapp.u
i/.ThemeListActivity: pid=1466 uid=10066 gids={3003, 1015}
I/ActivityManager(  146): Low Memory: No more background processes.
D/dalvikvm(  126): GC(1) freed 302 objects / 11512 bytes in 141ms
D/dalvikvm(  126): GC(1) freed 57 objects / 2560 bytes in 101ms
D/dalvikvm(  126): GC(1) freed 2 objects / 48 bytes in 109ms
W/UsageStats(  146): Something wrong here, didn't expect cmupdaterapp.ui to
be r
esumed
D/cmupdater( 1466): ThemeListActivity: Opening Database
W/InputManagerService(  146): Got RemoteException sending setActive(false)
notif
ication to pid 1437 uid 10066
I/ActivityManager(  146): Displayed activity
cmupdaterapp.ui/.ThemeListActivity:
 933 ms (total 96670 ms)
D/AnySoftKeyboard( 1248): Event: Key:82 Shift:false ALT:false Repeats:0
D/AnySoftKeyboard( 1248): makeKeyboards: force:false maxWidth:320
mLastDisplayWi
dth320
D/AnySoftKeyboard( 1248): makeKeyboards: force:false maxWidth:320
mLastDisplayWi
dth320
D/AnySoftKeyborad( 1248): Asking '╫נ╫á╫ע╫£╫ש╫¬' to translate 
key: 82
V/AnySoftKeyboard( 1248): Hard Keyboard Action before translation: Shift:
false,
 Alt: false, Key code: 82, changed: false
V/AnySoftKeyboard( 1248): Hard Keyboard Action after translation: Shift: false,
Alt: false, Key code: 82, changed: false
D/AnySoftKeyborad( 1248): '╫נ╫á╫ע╫£╫ש╫¬' did not translated 
key 82.
I/ActivityManager(  146): Starting activity: Intent {
cmp=cmupdaterapp.ui/.Theme
ListNewActivity (has extras) }
D/AndroidRuntime( 1466): Shutting down VM
W/dalvikvm( 1466): threadid=3: thread exiting with uncaught exception
(group=0x4
001e1c0)
E/AndroidRuntime( 1466): Uncaught handler: thread main exiting due to
uncaught e
xception
E/AndroidRuntime( 1466): java.lang.RuntimeException: Unable to start
activity Co
mponentInfo{cmupdaterapp.ui/cmupdaterapp.ui.ThemeListNewActivity}:
java.lang.Nul
lPointerException
E/AndroidRuntime( 1466):        at
android.app.ActivityThread.performLaunchActiv
ity(ActivityThread.java:2401)
E/AndroidRuntime( 1466):        at
android.app.ActivityThread.handleLaunchActivi
ty(ActivityThread.java:2417)
E/AndroidRuntime( 1466):        at
android.app.ActivityThread.access$2100(Activi
tyThread.java:116)
E/AndroidRuntime( 1466):        at
android.app.ActivityThread$H.handleMessage(Ac
tivityThread.java:1794)
E/AndroidRuntime( 1466):        at
android.os.Handler.dispatchMessage(Handler.ja
va:99)
E/AndroidRuntime( 1466):        at android.os.Looper.loop(Looper.java:123)
E/AndroidRuntime( 1466):        at
android.app.ActivityThread.main(ActivityThrea
d.java:4203)
E/AndroidRuntime( 1466):        at java.lang.reflect.Method.invokeNative(Native
Method)
E/AndroidRuntime( 1466):        at
java.lang.reflect.Method.invoke(Method.java:5
21)
E/AndroidRuntime( 1466):        at
com.android.internal.os.ZygoteInit$MethodAndA
rgsCaller.run(ZygoteInit.java:791)
E/AndroidRuntime( 1466):        at
com.android.internal.os.ZygoteInit.main(Zygot
eInit.java:549)
E/AndroidRuntime( 1466):        at dalvik.system.NativeStart.main(Native
Method)

E/AndroidRuntime( 1466): Caused by: java.lang.NullPointerException
E/AndroidRuntime( 1466):        at
cmupdaterapp.ui.ThemeListNewActivity.onCreate
(ThemeListNewActivity.java:45)
E/AndroidRuntime( 1466):        at
android.app.Instrumentation.callActivityOnCre
ate(Instrumentation.java:1123)
E/AndroidRuntime( 1466):        at
android.app.ActivityThread.performLaunchActiv
ity(ActivityThread.java:2364)
E/AndroidRuntime( 1466):        ... 11 more
I/Process (  146): Sending signal. PID: 1466 SIG: 3
I/dalvikvm( 1466): threadid=7: reacting to signal 3
I/dalvikvm( 1466): Wrote stack trace to '/data/anr/traces.txt'
W/ActivityManager(  146): Launch timeout has expired, giving up wake lock!
W/ActivityManager(  146): Activity idle timeout for HistoryRecord{43b17598
cmupd
aterapp.ui/.ThemeListNewActivity}
W/AnySoftKeyboard( 1248): The OS has reported that it is low on memory!.
I'll tr
y to clear some cache.
D/AnySoftKeyboard( 1248): makeKeyboards: force:false maxWidth:320
mLastDisplayWi
dth320
D/dalvikvm( 1248): GC(1) freed 274 objects / 16424 bytes in 275ms
===========================================================================
If you get a Force close do an: adb logcat
If somethings wrong in the app do an: adb logcat cmupdater:V *:S
For older Versions of the updater: adb logcat | grep "<CM-Updater>"


Please provide any additional information below.

```

Original issue reported on code.google.com by `RoyBar...@gmail.com` on 18 Oct 2009 at 10:14

**Comment by GoogleCodeExporter** [comment]
```
fixed
```

Original comment by `FireFart` on 25 Oct 2009 at 9:38
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
man you are awesome
```

Original comment by `RoyBar...@gmail.com` on 26 Oct 2009 at 3:05

**Comment by GoogleCodeExporter** [comment]
Original comment by `FireFart` on 28 Oct 2009 at 10:17
- Changed state: **Verified**
