### ISSUE TITLE
Null Pointer Exception in ApplyUploadActivity

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hoanglanton/cyanogen-updater#15]
```
After downloading an update, a Null reference Exception occours. Revision 61

Its because getIntent() = null.

E/AndroidRuntime( 5441): Uncaught handler: thread main exiting due to
uncaught exception
E/AndroidRuntime( 5441): java.lang.RuntimeException: Unable to instantiate
activity ComponentInfo{cmupdater.ui/cmupdater.ui.ApplyUploadActivity}:
java.lang.NullPointerException
E/AndroidRuntime( 5441):     at
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2194)
E/AndroidRuntime( 5441):     at
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2284)
E/AndroidRuntime( 5441):     at
android.app.ActivityThread.access$1800(ActivityThread.java:112)
E/AndroidRuntime( 5441):     at
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1692)
E/AndroidRuntime( 5441):     at
android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 5441):     at android.os.Looper.loop(Looper.java:123)
E/AndroidRuntime( 5441):     at
android.app.ActivityThread.main(ActivityThread.java:3948)
E/AndroidRuntime( 5441):     at
java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 5441):     at
java.lang.reflect.Method.invoke(Method.java:521)
E/AndroidRuntime( 5441):     at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:782)
E/AndroidRuntime( 5441):     at
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:540)
E/AndroidRuntime( 5441):     at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 5441): Caused by: java.lang.NullPointerException
E/AndroidRuntime( 5441):     at
cmupdater.ui.ApplyUploadActivity$ApplyUpdateListener.<init>(ApplyUploadActivity.
java:79)
E/AndroidRuntime( 5441):     at
cmupdater.ui.ApplyUploadActivity.<init>(ApplyUploadActivity.java:74)
E/AndroidRuntime( 5441):     at java.lang.Class.newInstanceImpl(Native Method)
E/AndroidRuntime( 5441):     at java.lang.Class.newInstance(Class.java:1472)
E/AndroidRuntime( 5441):     at
android.app.Instrumentation.newActivity(Instrumentation.java:1097)
E/AndroidRuntime( 5441):     at
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2186)
E/AndroidRuntime( 5441):     ... 11 more
```

Original issue reported on code.google.com by `FireFart` on 7 Aug 2009 at 2:30

**Comment by GoogleCodeExporter** [comment]
Original comment by `FireFart` on 7 Aug 2009 at 3:33
- Changed state: **New**

**Comment by GoogleCodeExporter** [comment]
Original comment by `christopher.banes@gmail.com` on 7 Aug 2009 at 10:07
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `FireFart` on 7 Aug 2009 at 10:08
- Changed state: **Verified**

**Comment by GoogleCodeExporter** [comment]
Original comment by `FireFart` on 8 Aug 2009 at 7:56
- Added labels: **Target_1.2**

**Comment by GoogleCodeExporter** [comment]
Original comment by `FireFart` on 10 Aug 2009 at 7:12
- Added labels: **Target_2.0**

**Comment by GoogleCodeExporter** [comment]
Original comment by `FireFart` on 10 Aug 2009 at 7:13
- Removed labels: **Target_1.2**
