### ISSUE TITLE
Problem when updating. Keeps telling MD5 error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hoanglanton/cyanogen-updater#152]
```
First this is not a Bugtracker for Cyanogen-Rom Bugs. Only for the updater.
The other Bugtracker can be found here:
http://code.google.com/p/cyanogenmod/issues/list

What steps will reproduce the problem?
1. Tap on Cyanogen 4.2.9.1
2. Starts downloading
3. When the download is finished, MD5 verification failed.
4. Starts downloading
5. When the download is finished, MD5 verification failed.
6. Starts downloading
7. When the download is finished, MD5 verification failed.
[...]
What is the expected output? What do you see instead?
Install the update. I see a loop download

What ROM are you running?(including Version) Previous one

What Version of CM-Updater are you running??(When using an Experimental
one, please Provide the SVN Release Number) Last one

Please provide a logcat of the issue:

D/cmupdater(11358): UpdateDownloaderService: Download finished
D/cmupdater(11358): UpdateDownloaderService: Consuming entity....
D/cmupdater(11358): UpdateDownloaderService: Entity consumed
D/cmupdater(11358): UpdateDownloaderService: Update download finished
D/cmupdater(11358): UpdateDownloaderService: Performing MD5 verification
D/dalvikvm(11358): GC freed 1480 objects / 117560 bytes in 107ms
D/cmupdater(11358): MD5: Calculated digest: 7553f569c11c9faace56b378a5425b5d
D/cmupdater(11358): MD5: Provided digest: 7a662935f1b1855080aca77d7cdb285d
E/cmupdater(11358): UpdateDownloaderService: An error occured while downloading 
the update 
file. Trying next mirror
E/cmupdater(11358): java.io.IOException: MD5 verification failed
E/cmupdater(11358):     at 
cmupdaterapp.service.UpdateDownloaderService.downloadFile(UpdateDownloaderServic
e.java:54
0)
E/cmupdater(11358):     at 
cmupdaterapp.service.UpdateDownloaderService.checkForConnectionAndUpdate(UpdateD
ownloa
derService.java:331)
E/cmupdater(11358):     at 
cmupdaterapp.service.UpdateDownloaderService.access$5(UpdateDownloaderService.ja
va:301)
E/cmupdater(11358):     at 
cmupdaterapp.service.UpdateDownloaderService$ServiceHandler.handleMessage(Update
Downloa
derService.java:164)
E/cmupdater(11358):     at android.os.Handler.dispatchMessage(Handler.java:99)
E/cmupdater(11358):     at android.os.Looper.loop(Looper.java:123)
E/cmupdater(11358):     at android.os.HandlerThread.run(HandlerThread.java:60)
I/NotificationService(  112): enqueueToast pkg=cmupdaterapp.ui 
callback=android.app.ITransientNotification$Stub$Proxy@43e3d258 duration=1
D/cmupdater(11358): UpdateDownloaderService: Mirrorname: n0rp.chemlab.org
D/cmupdater(11358): UpdateDownloaderService: mFileName: 
update-cm-4.2.9.1-signed.zip
D/cmupdater(11358): UpdateDownloaderService: Trying to download md5sum file 
from 
http://n0rp.chemlab.org/android/experimental/update-cm-4.2.9.1-signed.zip.md5sum
D/cmupdater(11358): UpdateDownloaderService: Trying to download update zip from 
http://n0rp.chemlab.org/android/experimental/update-cm-4.2.9.1-signed.zip
D/cmupdater(11358): UpdateDownloaderService: File not found on Server. Trying 
next one.
D/cmupdater(11358): UpdateDownloaderService: Mirrorname: www.androidspin.com
D/cmupdater(11358): UpdateDownloaderService: mFileName: 
update-cm-4.2.9.1-signed.zip
D/cmupdater(11358): UpdateDownloaderService: Trying to download md5sum file 
from 
http://www.androidspin.com/files/cyanogen/ROM/update-cm-4.2.9.1-signed.zip.md5su
m
W/SingleClientConnManager(11358): Invalid use of SingleClientConnManager: 
connection still 
allocated.
W/SingleClientConnManager(11358): Make sure to release the connection before 
allocating 
another one.
D/dalvikvm(11358): GC freed 1211 objects / 444416 bytes in 112ms
D/cmupdater(11358): UpdateDownloaderService: Trying to download update zip from 
http://www.androidspin.com/files/cyanogen/ROM/update-cm-4.2.9.1-signed.zip
W/SingleClientConnManager(11358): Invalid use of SingleClientConnManager: 
connection still 
allocated.
W/SingleClientConnManager(11358): Make sure to release the connection before 
allocating 
another one.
D/cmupdater(11358): UpdateDownloaderService: Trying to Read MD5 hash from 
response
I/global  (11358): Default buffer size used in BufferedReader constructor. It 
would be better to 
be explicit if an 8k-char buffer is required.
D/cmupdater(11358): UpdateDownloaderService: MD5: 
7a662935f1b1855080aca77d7cdb285d
D/cmupdater(11358): UpdateDownloaderService: Writing the calculated MD5 to disk
D/cmupdater(11358): UpdateDownloaderService: DumpFile Called
D/cmupdater(11358): UpdateDownloaderService: Update size: 38546KB


If you get a Force close do an: adb logcat
If somethings wrong in the app do an: adb logcat cmupdater:V *:S
For older Versions of the updater: adb logcat | grep "<CM-Updater>"


Please provide any additional information below.

```

Original issue reported on code.google.com by `marcos...@gmail.com` on 18 Dec 2009 at 11:23

**Comment by GoogleCodeExporter** [comment]
```
maybe there was a missplaced md5sum file. Works for me on the latest roms
```

Original comment by `FireFart` on 11 Jan 2010 at 5:51
- Changed state: **WorksForMe**

**Comment by GoogleCodeExporter** [comment]
Original comment by `FireFart` on 17 Feb 2010 at 6:38
- Changed state: **Verified**

**Comment by GoogleCodeExporter** [comment]
```
My f***** phone operator limits downloads to 5MB download on 3G/Edge ...
So CM Updater failed because the .zip is only 5MB...
Check if this is the same problem ...
```

Original comment by `dola...@gmail.com` on 5 Mar 2010 at 3:00
