### ISSUE TITLE
null pointer

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hoanglanton/cyanogen-updater#158]
```
seems a second service is started with ui == null --> KABOOOMM

I/ActivityManager( 1964): Starting activity: Intent { 
act=android.intent.action.MAIN 
cat=[android.intent.category.LAUNCHER] flg=0x10200000 
cmp=cmupdaterapp.ui/.MainActivity }
I/ActivityManager( 1964): Start proc cmupdaterapp.ui for activity 
cmupdaterapp.ui/.MainActivity: 
pid=9312 uid=10089 gids={3003, 1015}
D/cmupdater( 9312): MainActivity: onCreate called
D/cmupdater( 9312): Preferences: Preference Instance set.
D/cmupdater( 9312): Preferences: Board: trout
D/cmupdater( 9312): PlainTextUpdateServer: System's Mod version:trout
D/cmupdater( 9312): MainActivity: onStart called
D/cmupdater( 9312): MainActivity: onResume called
D/cmupdater( 9312): MainActivity: No Intent. Starting App in Default mode
D/cmupdater( 9312): Preferences: UpdateFolder: cmupdater/updates
D/cmupdater( 9312): State: Called LoadState
D/cmupdater( 9312): Preferences: Opening Database
D/cmupdater( 9312): Preferences: Closing Database
D/cmupdater( 9312): Preferences: Display Experimental Rom Updates: true
D/cmupdater( 9312): Preferences: Display All Rom Updates: true
D/cmupdater( 9312): Preferences: Display Experimental Theme Updates: true
D/cmupdater( 9312): Preferences: Display All Theme Updates: true
I/ActivityManager( 1964): Displayed activity cmupdaterapp.ui/.MainActivity: 
2479 ms (total 2479 
ms)
D/cmupdater( 9312): Preferences: ThemeFile: /system/framework/themes.theme
D/cmupdater( 9312): Preferences: No Theme File found. Using Wildcard for Theme 
Updates 
instead
D/cmupdater( 9312): Preferences: Display Experimental Rom Updates: true
D/cmupdater( 9312): Preferences: Display All Rom Updates: true
D/cmupdater( 9312): Preferences: Display Experimental Theme Updates: true
D/cmupdater( 9312): Preferences: Display All Theme Updates: true
D/cmupdater( 9312): Preferences: Opening Database
D/cmupdater( 9312): Preferences: Closing Database
D/cmupdater( 9312): PlainTextUpdateServer: Wildcard is used for Theme Updates
D/cmupdater( 9312): Preferences: Rom MetadataFile-Url: http://cyanogen-
updater.googlecode.com/files/update_file.json
D/cmupdater( 9312): Preferences: Opening Database
D/cmupdater( 9312): Preferences: Closing Database
D/cmupdater( 9312): PlainTextUpdateServer: Trying to download ThemeInfos for 
http://www.boooooddhsagcshfsr.com
E/cmupdater( 9312): PlainTextUpdateServer: There was an error downloading Theme 
sf: 
E/cmupdater( 9312): java.net.UnknownHostException: Host is unresolved: 
www.boooooddhsagcshfsr.com:80
E/cmupdater( 9312):     at java.net.Socket.connect(Socket.java:1037)
E/cmupdater( 9312):     at 
org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.
java:117)
E/cmupdater( 9312):     at 
org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(Default
ClientConne
ctionOperator.java:129)
E/cmupdater( 9312):     at 
org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
E/cmupdater( 9312):     at 
org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapt
er.java:11
9)
E/cmupdater( 9312):     at 
org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirecto
r.java:348)
E/cmupdater( 9312):     at 
org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:5
55)
E/cmupdater( 9312):     at 
org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:4
87)
E/cmupdater( 9312):     at 
org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:4
65)
E/cmupdater( 9312):     at 
cmupdaterapp.service.PlainTextUpdateServer.getAvailableUpdates(PlainTextUpdateSe
rver.java:14
1)
E/cmupdater( 9312):     at cmupdaterapp.tasks.UpdateCheck.run(UpdateCheck.java:48)
E/cmupdater( 9312):     at java.lang.Thread.run(Thread.java:1096)
D/cmupdater( 9312): PlainTextUpdateServer: Trying to download ThemeInfos for 
http://cyanogen-updater.googlecode.com/files/ThemeTest.json
D/cmupdater( 9312): PlainTextUpdateServer: Found 1 mirrors in the JSON
D/cmupdater( 9312): PlainTextUpdateServer: Found 1 updates in the JSON
D/cmupdater( 9312): PlainTextUpdateServer: Discarding Theme (rom mismatch) 
MarksTheme: 
Your Theme: null null; From JSON: MarksTheme 4.2.3.1.a
D/cmupdater( 9312): PlainTextUpdateServer: Found 8 mirrors in the JSON
D/cmupdater( 9312): PlainTextUpdateServer: Found 12 updates in the JSON
D/cmupdater( 9312): PlainTextUpdateServer: Adding Rom: CyanogenMod-4.2.11.1 
Version: 
4.2.11.1 Filename: update-cm-4.2.11.1-signed.zip
D/cmupdater( 9312): PlainTextUpdateServer: Adding Rom: CyanogenMod-4.2.10.1 
Version: 
4.2.10.1 Filename: update-cm-4.2.10.1-signed.zip
D/cmupdater( 9312): PlainTextUpdateServer: Adding Rom: CyanogenMod-4.2.9.1 
Version: 
4.2.9.1 Filename: update-cm-4.2.9.1-signed.zip
D/cmupdater( 9312): PlainTextUpdateServer: Adding Rom: CyanogenMod-4.2.8.1 
Version: 
4.2.8.1 Filename: update-cm-4.2.8.1-signed.zip
D/cmupdater( 9312): PlainTextUpdateServer: Adding Rom: CyanogenMod-4.2.8 
Version: 4.2.8 
Filename: update-cm-4.2.8-signed.zip
D/cmupdater( 9312): PlainTextUpdateServer: Adding Rom: CyanogenMod-4.2.7.1 
Version: 
4.2.7.1 Filename: update-cm-4.2.7.1-signed.zip
D/cmupdater( 9312): PlainTextUpdateServer: Adding Rom: CyanogenMod-4.2.6 
Version: 4.2.6 
Filename: update-cm-4.2.6-signed.zip
D/cmupdater( 9312): PlainTextUpdateServer: Adding Rom: CyanogenMod-4.2.5 
Version: 4.2.5 
Filename: update-cm-4.2.5-signed.zip
D/cmupdater( 9312): PlainTextUpdateServer: Adding Rom: CyanogenMod-4.2.4 
Version: 4.2.4 
Filename: update-cm-4.2.4-signed.zip
D/cmupdater( 9312): PlainTextUpdateServer: Adding Rom: CyanogenMod-4.2.3.1 
Version: 
4.2.3.1 Filename: update-cm-4.2.3.1-signed.zip
D/cmupdater( 9312): PlainTextUpdateServer: Adding Rom: CyanogenMod-4.2.2 
Version: 4.2.2 
Filename: update-cm-4.2.2-signed.zip
D/cmupdater( 9312): PlainTextUpdateServer: Adding Rom: CyanogenMod-4.2.1 
Version: 4.2.1 
Filename: update-cm-4.2.1-signed.zip
D/cmupdater( 9312): State: Called LoadState
D/cmupdater( 9312): PlainTextUpdateServer: Called FilterUpdates
D/cmupdater( 9312): State: Called SaveState
I/NotificationService( 1964): enqueueToast pkg=cmupdaterapp.ui 
callback=android.app.ITransientNotification$Stub$Proxy@43cb1950 duration=1
D/cmupdater( 9312): UpdateCheck: 1 ROM update(s) found; 0 Theme update(s) found
D/cmupdater( 9312): State: Called LoadState
D/cmupdater( 9312): Preferences: Opening Database
D/cmupdater( 9312): Preferences: Closing Database
D/cmupdater( 9312): Preferences: Display Experimental Rom Updates: true
D/cmupdater( 9312): Preferences: Display All Rom Updates: true
D/cmupdater( 9312): Preferences: Display Experimental Theme Updates: true
D/cmupdater( 9312): Preferences: Display All Theme Updates: true
D/cmupdater( 9312): Preferences: Notifications Enabled: true
D/cmupdater( 9312): Preferences: Notification Vibrate: true
D/cmupdater( 9312): MainActivity: Download Rom Button clicked
I/ActivityManager( 1964): Starting activity: Intent { 
cmp=cmupdaterapp.ui/.DownloadActivity (has 
extras) }
I/NotificationService( 1964): enqueueToast pkg=cmupdaterapp.ui 
callback=android.app.ITransientNotification$Stub$Proxy@43a6d7c8 duration=1
D/cmupdater( 9312): DownloadActivity: onCreate called
D/cmupdater( 9312): DownloadActivity: onStart called
D/cmupdater( 9312): DownloadActivity: onResume called
D/cmupdater( 9312): DownloadActivity: Not downloading
D/cmupdater( 9312): UpdateDownloaderService: Download Service Created
D/cmupdater( 9312): Preferences: UpdateFolder: cmupdater/updates
D/cmupdater( 9312): Preferences: ProgressUpdateFrequency: 500
D/cmupdater( 9312): UpdateDownloaderService: ProgressBarIntervall: 500
D/cmupdater( 9312): UpdateDownloaderService: Download Service started
D/cmupdater( 9312): UpdateDownloaderService: Starting #1: 
Bundle[mParcelledData.dataSize=1676]
D/cmupdater( 9312): UpdateDownloaderService: Sending: { what=0 when=0 arg1=1 
obj=Bundle[mParcelledData.dataSize=1676] }
D/cmupdater( 9312): UpdateDownloaderService: Download Service onBind was called
D/cmupdater( 9312): UpdateDownloaderService: Request Download Update Message 
was 
recieved
D/cmupdater( 9312): UpdateDownloaderService: Called CheckForConnectionAndUpdate
D/cmupdater( 9312): UpdateDownloaderService: Downloading update...
D/cmupdater( 9312): UpdateDownloaderService: Called downloadFile
D/cmupdater( 9312): UpdateDownloaderService: Mirrorcount: 8
D/cmupdater( 9312): UpdateDownloaderService: Mirrorname: n0rp.chemlab.org
D/cmupdater( 9312): UpdateDownloaderService: mFileName: 
update-cm-4.2.11.1-signed.zip
D/cmupdater( 9312): UpdateDownloaderService: Trying to download md5sum file 
from 
http://n0rp.chemlab.org/android/experimental/update-cm-4.2.11.1-signed.zip.md5su
m
I/ActivityManager( 1964): Displayed activity cmupdaterapp.ui/.DownloadActivity: 
815 ms (total 
815 ms)
D/cmupdater( 9312): MainActivity: onStop called
D/cmupdater( 9312): MainActivity: App closed
D/cmupdater( 9312): UpdateDownloaderService: Trying to download update zip from 
http://n0rp.chemlab.org/android/experimental/update-cm-4.2.11.1-signed.zip
D/cmupdater( 9312): UpdateDownloaderService: File not found on Server. Trying 
next one.
D/cmupdater( 9312): UpdateDownloaderService: Mirrorname: www.androidspin.com
D/cmupdater( 9312): UpdateDownloaderService: mFileName: 
update-cm-4.2.11.1-signed.zip
D/cmupdater( 9312): UpdateDownloaderService: Trying to download md5sum file 
from 
http://www.androidspin.com/files/cyanogen/ROM/update-cm-4.2.11.1-signed.zip.md5s
um
D/cmupdater( 9312): UpdateDownloaderService: Trying to download update zip from 
http://www.androidspin.com/files/cyanogen/ROM/update-cm-4.2.11.1-signed.zip
D/cmupdater( 9312): UpdateDownloaderService: Trying to Read MD5 hash from 
response
D/cmupdater( 9312): UpdateDownloaderService: MD5: 
9407a34f0a6429b5a44430b17379d433
D/cmupdater( 9312): UpdateDownloaderService: Writing the calculated MD5 to disk
D/cmupdater( 9312): UpdateDownloaderService: DumpFile Called
D/cmupdater( 9312): UpdateDownloaderService: Update size: 38033KB
D/cmupdater( 9312): DownloadActivity: Orientation Changed. New Orientation: 2
D/cmupdater( 9312): DownloadActivity: Orientation Changed. New Orientation: 1
W/WindowManager( 1964): Force clearing orientation change: Window{43bae510 
cmupdaterapp.ui/cmupdaterapp.ui.DownloadActivity paused=false}
I/ActivityManager( 1964): Process cmupdaterapp.ui (pid 9312) has died.
W/ActivityManager( 1964): Scheduling restart of crashed service 
cmupdaterapp.ui/cmupdaterapp.service.UpdateDownloaderService in 5000ms
I/WindowManager( 1964): WIN DEATH: Window{43b35c08 
cmupdaterapp.ui/cmupdaterapp.ui.MainActivity paused=false}
I/WindowManager( 1964): WIN DEATH: Window{43bae510 
cmupdaterapp.ui/cmupdaterapp.ui.DownloadActivity paused=false}
I/ActivityManager( 1964): Start proc cmupdaterapp.ui for service 
cmupdaterapp.ui/cmupdaterapp.service.UpdateDownloaderService: pid=9504 
uid=10089 
gids={3003, 1015}
D/cmupdater( 9504): UpdateDownloaderService: Download Service Created
D/cmupdater( 9504): Preferences: Preference Instance set.
D/cmupdater( 9504): Preferences: UpdateFolder: cmupdater/updates
D/cmupdater( 9504): Preferences: ProgressUpdateFrequency: 500
D/cmupdater( 9504): UpdateDownloaderService: ProgressBarIntervall: 500
I/ActivityManager( 1964): Starting activity: Intent { 
cmp=cmupdaterapp.ui/.DownloadActivity }
W/ActivityManager( 1964): startActivity called from non-Activity context; 
forcing 
Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { 
cmp=cmupdaterapp.ui/.DownloadActivity }
D/cmupdater( 9504): DownloadActivity: onCreate called
D/cmupdater( 9504): DownloadActivity: onStart called
D/cmupdater( 9504): DownloadActivity: onResume called
D/cmupdater( 9504): DownloadActivity: Not downloading
E/AndroidRuntime( 9504): java.lang.RuntimeException: Unable to resume activity 
{cmupdaterapp.ui/cmupdaterapp.ui.DownloadActivity}: 
java.lang.NullPointerException
E/AndroidRuntime( 9504):    at 
cmupdaterapp.ui.DownloadActivity.onResume(DownloadActivity.java:115)
I/ActivityManager( 1964): Process cmupdaterapp.ui (pid 9504) has died.
W/ActivityManager( 1964): Scheduling restart of crashed service 
cmupdaterapp.ui/cmupdaterapp.service.UpdateDownloaderService in 11018ms
I/ActivityManager( 1964): Start proc cmupdaterapp.ui for activity 
cmupdaterapp.ui/.DownloadActivity: pid=9556 uid=10089 gids={3003, 1015}
W/UsageStats( 1964): Something wrong here, didn't expect cmupdaterapp.ui to be 
resumed
D/cmupdater( 9556): DownloadActivity: onCreate called
D/cmupdater( 9556): DownloadActivity: onStart called
D/cmupdater( 9556): DownloadActivity: onResume called
D/cmupdater( 9556): DownloadActivity: Not downloading
D/cmupdater( 9556): UpdateDownloaderService: Download Service Created
D/cmupdater( 9556): Preferences: Preference Instance set.
D/cmupdater( 9556): Preferences: UpdateFolder: cmupdater/updates
D/cmupdater( 9556): Preferences: ProgressUpdateFrequency: 500
D/cmupdater( 9556): UpdateDownloaderService: ProgressBarIntervall: 500
D/cmupdater( 9556): UpdateDownloaderService: Download Service started
D/cmupdater( 9556): UpdateDownloaderService: Starting #2: 
Bundle[mParcelledData.dataSize=136]
D/cmupdater( 9556): UpdateDownloaderService: Sending: { what=0 when=0 arg1=2 
obj=Bundle[mParcelledData.dataSize=136] }
D/cmupdater( 9556): UpdateDownloaderService: Request Download Update Message 
was 
recieved
D/cmupdater( 9556): UpdateDownloaderService: Called CheckForConnectionAndUpdate
D/cmupdater( 9556): UpdateDownloaderService: Download Service started
D/cmupdater( 9556): UpdateDownloaderService: Starting #3: 
Bundle[mParcelledData.dataSize=1676]
D/cmupdater( 9556): UpdateDownloaderService: Sending: { what=0 when=0 arg1=3 
obj=Bundle[mParcelledData.dataSize=1676] }
D/cmupdater( 9556): UpdateDownloaderService: Download Service onBind was called
I/ActivityManager( 1964): Displayed activity cmupdaterapp.ui/.DownloadActivity: 
1423 ms (total 
5323 ms)
D/cmupdater( 9556): UpdateDownloaderService: Downloading update...
D/cmupdater( 9556): UpdateDownloaderService: Called downloadFile
E/cmupdater( 9556): UpdateDownloaderService: RuntimeEx while checking for 
updates
E/cmupdater( 9556): java.lang.NullPointerException
E/cmupdater( 9556):     at 
cmupdaterapp.service.UpdateDownloaderService.downloadFile(UpdateDownloaderServic
e.java:41
2)
E/cmupdater( 9556):     at 
cmupdaterapp.service.UpdateDownloaderService.checkForConnectionAndUpdate(UpdateD
ownloa
derService.java:331)
E/cmupdater( 9556):     at 
cmupdaterapp.service.UpdateDownloaderService.access$5(UpdateDownloaderService.ja
va:301)
E/cmupdater( 9556):     at 
cmupdaterapp.service.UpdateDownloaderService$ServiceHandler.handleMessage(Update
Downloa
derService.java:164)
E/cmupdater( 9556):     at android.os.Handler.dispatchMessage(Handler.java:99)
E/cmupdater( 9556):     at android.os.Looper.loop(Looper.java:123)
E/cmupdater( 9556):     at android.os.HandlerThread.run(HandlerThread.java:60)
D/cmupdater( 9556): Preferences: Notification Vibrate: true
D/cmupdater( 9556): UpdateDownloaderService: Called Notify User
D/cmupdater( 9556): UpdateDownloaderService: Downloaded Update was NULL
D/cmupdater( 9556): UpdateDownloaderService: Download Notification removed
I/ActivityManager( 1964): Starting activity: Intent { flg=0x10000000 
cmp=cmupdaterapp.ui/.MainActivity (has extras) }
W/ActivityManager( 1964): Duplicate finish request for HistoryRecord{43ce3698 
cmupdaterapp.ui/.DownloadActivity}
D/cmupdater( 9556): UpdateDownloaderService: Done with #2
D/cmupdater( 9556): MainActivity: onCreate called
D/cmupdater( 9556): UpdateDownloaderService: Request Download Update Message 
was 
recieved
D/cmupdater( 9556): UpdateDownloaderService: Called CheckForConnectionAndUpdate
D/cmupdater( 9556): Preferences: Board: trout
D/cmupdater( 9556): PlainTextUpdateServer: System's Mod version:trout
D/cmupdater( 9556): MainActivity: onStart called
D/cmupdater( 9556): MainActivity: onResume called
D/cmupdater( 9556): MainActivity: No Intent. Starting App in Default mode
D/cmupdater( 9556): Preferences: UpdateFolder: cmupdater/updates
I/ActivityManager( 1964): Starting activity: Intent { 
cmp=cmupdaterapp.ui/.DownloadActivity (has 
extras) }
D/cmupdater( 9556): UpdateDownloaderService: Downloading update...
D/cmupdater( 9556): UpdateDownloaderService: Called downloadFile
D/cmupdater( 9556): UpdateDownloaderService: Mirrorcount: 8
D/cmupdater( 9556): UpdateDownloaderService: Mirrorname: cyanogen-
updater.googlecode.com
D/cmupdater( 9556): UpdateDownloaderService

```

Original issue reported on code.google.com by `FireFart` on 28 Dec 2009 at 12:30

**Comment by GoogleCodeExporter** [comment]
```
fixed
```

Original comment by `FireFart` on 13 Jan 2010 at 5:58
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `FireFart` on 17 Feb 2010 at 6:38
- Changed state: **Verified**
