### ISSUE TITLE
Floce close when trying to verify an update.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hoanglanton/cyanogen-updater#17]
```
While verifying an update a force close occours.

I/ActivityManager( 3622): Starting activity: Intent {
action=android.intent.action.MAIN
categories={android.intent.category.LAUNCHER} flags=0x10200000
comp={cmupdater.ui/cmupdater.ui.UpdateProcessInfo} }
I/PlainTextUpdateServer( 3905): System's Mod version:ADP1
W/IInputConnectionWrapper( 3683): showStatusIcon on inactive InputConnection
I/ActivityManager( 3622): Displayed activity
cmupdater.ui/.UpdateProcessInfo: 654 ms
D/IOUtils ( 3905): md5sum exit value:0
W/dalvikvm( 3905): threadid=21: thread exiting with uncaught exception
(group=0x40019a68)
E/AndroidRuntime( 3905): Uncaught handler: thread UserTask #1 exiting due
to uncaught exception
E/AndroidRuntime( 3905): java.lang.RuntimeException: An error occured while
executing doInBackground()
E/AndroidRuntime( 3905):    at cmupdater.ui.UserTask$3.done(UserTask.java:204)
E/AndroidRuntime( 3905):    at
java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:234)
E/AndroidRuntime( 3905):    at
java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:258)
E/AndroidRuntime( 3905):    at
java.util.concurrent.FutureTask.run(FutureTask.java:122)
E/AndroidRuntime( 3905):    at
java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:6
48)
E/AndroidRuntime( 3905):    at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:673)
E/AndroidRuntime( 3905):    at java.lang.Thread.run(Thread.java:1060)
E/AndroidRuntime( 3905): Caused by: java.lang.NullPointerException
E/AndroidRuntime( 3905):    at
cmupdater.ui.UpdateProcessInfo$MD5CheckerTask.doInBackground(UpdateProcessInfo.j
ava:193)
E/AndroidRuntime( 3905):    at
cmupdater.ui.UpdateProcessInfo$MD5CheckerTask.doInBackground(UpdateProcessInfo.j
ava:1)
E/AndroidRuntime( 3905):    at cmupdater.ui.UserTask$2.call(UserTask.java:188)
E/AndroidRuntime( 3905):    at
java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:256)
E/AndroidRuntime( 3905):    ... 4 more
I/Process ( 3622): Sending signal. PID: 3905 SIG: 3
I/dalvikvm( 3905): threadid=7: reacting to signal 3
I/dalvikvm( 3905): Wrote stack trace to '/data/anr/traces.txt'
I/Process ( 3905): Sending signal. PID: 3905 SIG: 9
I/ActivityManager( 3622): Process cmupdater.ui (pid 3905) has died.
W/ActivityManager( 3622): Service crashed 2 times, stopping:
ServiceRecord{435d8d40 cmupdater.ui/cmupdater.service.UpdateCheckerService}
I/WindowManager( 3622): WIN DEATH: Window{437f1070 Verifying paused=false}
I/WindowManager( 3622): WIN DEATH: Window{437ae390
cmupdater.ui/cmupdater.ui.UpdateProcessInfo paused=false}
W/InputManagerService( 3622): Got RemoteException sending setActive(false)
notification to pid 3905 uid 10040
D/WifiService( 3622): ACTION_BATTERY_CHANGED pluggedType: 2

```

Original issue reported on code.google.com by `willmav5...@gmail.com` on 7 Aug 2009 at 5:51

**Comment by GoogleCodeExporter** [comment]
```
Its because ui.md5 is null(not provided via JSON File). The Procedure tries to 
verify the md5 value from the JSON 
file against the calculated one. --> Null reference Exception because JSON.md5 
= null

Im Going to remove this "an update.zip has been found" and replace it
```

Original comment by `FireFart` on 8 Aug 2009 at 1:34

**Comment by GoogleCodeExporter** [comment]
```
I agree, the function isn't needed anyway as the zip is verified after it's
downloaded anyway.
```

Original comment by `christopher.banes@gmail.com` on 8 Aug 2009 at 1:39

**Comment by GoogleCodeExporter** [comment]
```
Fixed
```

Original comment by `FireFart` on 8 Aug 2009 at 4:38
- Added labels: **Target_1.2**

**Comment by GoogleCodeExporter** [comment]
Original comment by `FireFart` on 8 Aug 2009 at 4:39
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `FireFart` on 10 Aug 2009 at 7:12
- Added labels: **Target_2.0**

**Comment by GoogleCodeExporter** [comment]
Original comment by `FireFart` on 10 Aug 2009 at 7:13
- Removed labels: **Target_1.2**

**Comment by GoogleCodeExporter** [comment]
Original comment by `FireFart` on 14 Aug 2009 at 8:18
- Changed state: **Verified**
