### ISSUE TITLE
Check for update fails with certificate error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hoanglanton/cyanogen-updater#192]
```
First this is not a Bugtracker for Cyanogen-Rom Bugs. Only for the updater.
The other Bugtracker can be found here:
http://code.google.com/p/cyanogenmod/issues/list

What steps will reproduce the problem?
1. Open CM Updater
2. Click "Check for updates"
3.

What is the expected output? What do you see instead?
I get an error that the certificate is invalid, because of a wrong hostname.
github.com != *.github.com

What ROM are you running?(including Version)
CyanogenMod-5.0.8-DS

What Version of CM-Updater are you running??(When using an Experimental
one, please Provide the SVN Release Number)
5.0.1

Please provide a logcat of the issue:
If you get a Force close do an: adb logcat
If somethings wrong in the app do an: adb logcat cmupdater:V *:S
For older Versions of the updater: adb logcat | grep "<CM-Updater>"

E/cmupdater( 4339): UpdateCheckService: IOEx while checking for updates         


E/cmupdater( 4339): javax.net.ssl.SSLException: hostname in certificate didn't 
match: <github.com> != <*.github.com>                                           

E/cmupdater( 4339):     at 
org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:222)     


E/cmupdater( 4339):     at 
org.apache.http.conn.ssl.BrowserCompatHostnameVerifier.verify(BrowserCompatHostn
ameVerifier.java:54)                                                            

E/cmupdater( 4339):     at 
org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:151)     


E/cmupdater( 4339):     at 
org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:132)     


E/cmupdater( 4339):     at 
org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:32
1)                                                                              

E/cmupdater( 4339):     at 
org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(Default
ClientConnectionOperator.java:129)                                              

E/cmupdater( 4339):     at 
org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)    


E/cmupdater( 4339):     at 
org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapt
er.java:119)                                                                    

E/cmupdater( 4339):     at 
org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirecto
r.java:348)                                                                     

E/cmupdater( 4339):     at 
org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:5
55)                                                                             

E/cmupdater( 4339):     at 
org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:4
87)                                                                             

E/cmupdater( 4339):     at 
org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:4
65)                                                                             

E/cmupdater( 4339):     at 
cmupdaterapp.service.UpdateCheckService.getAvailableUpdates(UpdateCheckService.j
ava:333)                                                                        

E/cmupdater( 4339):     at 
cmupdaterapp.service.UpdateCheckService.checkForNewUpdates(UpdateCheckService.ja
va:190)                                                                         

E/cmupdater( 4339):     at 
cmupdaterapp.service.UpdateCheckService.access$4(UpdateCheckService.java:165)   


E/cmupdater( 4339):     at 
cmupdaterapp.service.UpdateCheckService$1.checkForUpdates(UpdateCheckService.jav
a:151)                                                                          

E/cmupdater( 4339):     at 
cmupdaterapp.interfaces.IUpdateCheckService$Stub.onTransact(IUpdateCheckService.
java:54)                                                                        

E/cmupdater( 4339):     at android.os.Binder.execTransact(Binder.java:287)      


E/cmupdater( 4339):     at dalvik.system.NativeStart.run(Native Method)         


I/cmupdater( 4328): State: No State Info stored
Please provide any additional information below.

```

Original issue reported on code.google.com by `nick.sto...@gmail.com` on 5 Nov 2010 at 12:30

**Comment by GoogleCodeExporter** [comment]
```
I am having the same problem checking for updates on a Cliq XT (trying to 
update Vanilla 1.1.3 to 1.2.3). The error message is exactly the same: 
<github.com> != <*.github.com>

This was the only relevant result when I googled it, and it was posted 13 hours 
ago, so I'm hoping this is an issue with the github server itself that just 
arose today...
```

Original comment by `jonlev...@gmail.com` on 6 Nov 2010 at 2:28

**Comment by GoogleCodeExporter** [comment]
```
seems like this is a problem with the github certificate. Good to see that 
there are people out there using the updater since it is replaced by rommanager 
cause no one maintains the json file for the updater ;)
```

Original comment by `FireFart` on 7 Nov 2010 at 4:03

**Comment by GoogleCodeExporter** [comment]
```
It's not a problem with the cert; github is using a wildcard certificate, and 
the updater (or the library it uses to validate TLS/SSL connections) isn't 
smart enough to realize that an SSL cert valid for "*.github.com" is valid for 
"github.com" as well.
```

Original comment by `olcrag...@gmail.com` on 9 Nov 2010 at 8:15

**Comment by GoogleCodeExporter** [comment]
```
Also, I just downloaded the JSON manually and had a peek; it doesn't have 
anything more recent than 5.0.8-N1. :-(
```

Original comment by `olcrag...@gmail.com` on 9 Nov 2010 at 8:18

**Comment by GoogleCodeExporter** [comment]
```
Jeah but i'm using androids standard methods to download the json file. I have 
not found a solution for this problem
```

Original comment by `FireFart` on 9 Nov 2010 at 8:19

**Comment by GoogleCodeExporter** [comment]
```
Is there a way to add a certificate for github.com or to disable the validation 
entirely? I apologize if I'm abusing this forum but this is the only place 
that's getting me close to a solution...
```

Original comment by `jonlev...@gmail.com` on 9 Nov 2010 at 9:14

**Comment by GoogleCodeExporter** [comment]
```
I gave up. Since the owner (firefart) in comment #2 said "it is replaced by 
rommanager cause no one maintains the json file for the updater" I took that to 
mean effective EOL for the project. So I went and downloaded ROM Manager, which 
works almost as well and has up-to-date data.
```

Original comment by `olcrag...@gmail.com` on 11 Nov 2010 at 6:55

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
What ROM Manager do you download? There is no Rom Manager from Cyanogen. There 
is from other providers and I don't want to brick my phone ***Rogers HTC Magic.

Please advice.
```

Original comment by `bruceb...@gmail.com` on 20 Nov 2010 at 1:55

**Comment by GoogleCodeExporter** [comment]
```
ROM Manager doesn't support the Cliq XT. Others are doing OTA updates without 
problems so I'm wondering what's wrong with my install...
```

Original comment by `jonlev...@gmail.com` on 20 Nov 2010 at 3:23
