### ISSUE TITLE
Force close when trying to download.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hoanglanton/cyanogen-updater#22]
```
A force close occurs when pressing the download button in r82.

E/AndroidRuntime( 1280): Uncaught handler: thread main exiting due to
uncaught exception
E/AndroidRuntime( 1280): java.lang.NullPointerException
E/AndroidRuntime( 1280):    at
cmupdater.ui.UpdateProcessInfo.switchToDownloadingLayout(UpdateProcessInfo.java:
599)
E/AndroidRuntime( 1280):    at
cmupdater.ui.UpdateProcessInfo.downloadRequestedUpdate(UpdateProcessInfo.java:78
9)
E/AndroidRuntime( 1280):    at
cmupdater.ui.UpdateProcessInfo.access$3(UpdateProcessInfo.java:788)
E/AndroidRuntime( 1280):    at
cmupdater.ui.UpdateProcessInfo$2.onClick(UpdateProcessInfo.java:147)
E/AndroidRuntime( 1280):    at android.view.View.performClick(View.java:2179)
E/AndroidRuntime( 1280):    at android.view.View.onTouchEvent(View.java:3828)
E/AndroidRuntime( 1280):    at
android.widget.TextView.onTouchEvent(TextView.java:6291)
E/AndroidRuntime( 1280):    at
android.view.View.dispatchTouchEvent(View.java:3368)
E/AndroidRuntime( 1280):    at
android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:863)
E/AndroidRuntime( 1280):    at
android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:863)
E/AndroidRuntime( 1280):    at
android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:863)
E/AndroidRuntime( 1280):    at
android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:863)
E/AndroidRuntime( 1280):    at
android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:863)
E/AndroidRuntime( 1280):    at
com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(P
honeWindow.java:1707)
E/AndroidRuntime( 1280):    at
com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow
.java:1197)
E/AndroidRuntime( 1280):    at
android.app.Activity.dispatchTouchEvent(Activity.java:1993)
E/AndroidRuntime( 1280):    at
com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneW
indow.java:1691)
E/AndroidRuntime( 1280):    at
android.view.ViewRoot.handleMessage(ViewRoot.java:1525)
E/AndroidRuntime( 1280):    at
android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 1280):    at android.os.Looper.loop(Looper.java:123)
E/AndroidRuntime( 1280):    at
android.app.ActivityThread.main(ActivityThread.java:3948)
E/AndroidRuntime( 1280):    at java.lang.reflect.Method.invokeNative(Native
Method)
E/AndroidRuntime( 1280):    at java.lang.reflect.Method.invoke(Method.java:521)
E/AndroidRuntime( 1280):    at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:782)
E/AndroidRuntime( 1280):    at
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:540)
E/AndroidRuntime( 1280):    at dalvik.system.NativeStart.main(Native Method)

```

Original issue reported on code.google.com by `willmav5...@gmail.com` on 8 Aug 2009 at 5:18

**Comment by GoogleCodeExporter** [comment]
```
fixed in r83
```

Original comment by `FireFart` on 8 Aug 2009 at 6:26
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `FireFart` on 8 Aug 2009 at 7:57
- Added labels: **Target_1.2**

**Comment by GoogleCodeExporter** [comment]
Original comment by `FireFart` on 10 Aug 2009 at 7:12
- Added labels: **Target_2.0**

**Comment by GoogleCodeExporter** [comment]
Original comment by `FireFart` on 10 Aug 2009 at 7:13
- Removed labels: **Target_1.2**

**Comment by GoogleCodeExporter** [comment]
Original comment by `FireFart` on 14 Aug 2009 at 8:20
- Changed state: **Verified**
