### ISSUE TITLE
Exception when changing to Landscape Mode

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hoanglanton/cyanogen-updater#38]
```
When changing to Landscape Mode:
E/AndroidRuntime(  826): Uncaught handler: thread main exiting due to uncaught 
exception
E/AndroidRuntime(  826): java.lang.RuntimeException: Unable to stop activity 
{cmupdater.ui/cmupdater.ui.UpdateProcessInfo}: java.lang.NullPointerException
E/AndroidRuntime(  826):    at 
android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3097)
E/AndroidRuntime(  826):    at 
android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3159)
E/AndroidRuntime(  826):    at 
android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3252)
E/AndroidRuntime(  826):    at 
android.app.ActivityThread.access$1900(ActivityThread.java:112)
E/AndroidRuntime(  826):    at 
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
E/AndroidRuntime(  826):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(  826):    at android.os.Looper.loop(Looper.java:123)
E/AndroidRuntime(  826):    at 
android.app.ActivityThread.main(ActivityThread.java:3948)
E/AndroidRuntime(  826):    at java.lang.reflect.Method.invokeNative(Native 
Method)
E/AndroidRuntime(  826):    at java.lang.reflect.Method.invoke(Method.java:521)
E/AndroidRuntime(  826):    at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:782)
E/AndroidRuntime(  826):    at 
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:540)
E/AndroidRuntime(  826):    at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(  826): Caused by: java.lang.NullPointerException
E/AndroidRuntime(  826):    at 
cmupdater.ui.UpdateProcessInfo.onStop(UpdateProcessInfo.java:445)
E/AndroidRuntime(  826):    at 
android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1245)
E/AndroidRuntime(  826):    at 
android.app.Activity.performStop(Activity.java:3564)
E/AndroidRuntime(  826):    at 
android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3092)
E/AndroidRuntime(  826):    ... 12 more

```

Original issue reported on code.google.com by `FireFart` on 11 Aug 2009 at 8:07

**Comment by GoogleCodeExporter** [comment]
```
fixed.
Download also continues on orientation change
```

Original comment by `FireFart` on 11 Aug 2009 at 8:44
- Changed state: **Fixed**
- Added labels: **Target_2.1**

**Comment by GoogleCodeExporter** [comment]
Original comment by `FireFart` on 14 Aug 2009 at 8:20
- Changed state: **Verified**
